version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php -S 0.0.0.0:80 -t public'
    volumes:
      - .:/app
    environment:
      PMA_HOST: host.docker.internal
    ports:
      - "8000:80"
